mode: 2 # 1: print chapter numbers, other: get audio
epub:
  file: "in/in.epub"
out:
  chapter:
    start: 16
    end: 20
  path: "out"
  voice: "zh-CN-YunjianNeural"
  watermark: " this is the end of chapter thank you for listening"